#include:
 
#  - board: nice_nano_v2
#    shield: settings_reset
#  - board: corne_left
#    shield: nice_view_adapter nice_view
#    artifact-name: corne_left_nice_view
#  - board: corne_right
#    shield: nice_view_adapter nice_view
#    artifact-name: corne_right_nice_view

include:
  - board: nice_nano_v2
    shield: kyria_left nice_view_adapter nice_view_gem #updated entry
  - board: nice_nano_v2
    shield: kyria_right nice_view_adapter nice_view_gem #updated entry
